package dev.nilp0inter.subspace.ui

interface PttUiActions {
    fun requestPermissions()
    fun requestManageExternalStorage()
    fun pickCaptainsLogDirectory()
    fun openBluetoothSettings()
    fun scanForDevice()
    fun pairTarget()
    fun connectSerial()
    fun retry()
    fun disconnectSerial()
    fun setEchoEnabled(enabled: Boolean)
    fun setSttEnabled(enabled: Boolean)
    fun setTtsEnabled(enabled: Boolean)
    fun setSttTtsEnabled(enabled: Boolean)
    fun setCaptainsLogSaveVoice(enabled: Boolean)
    fun setCaptainsLogSaveText(enabled: Boolean)
    fun setCaptainsLogEnabled(enabled: Boolean)
    fun setTtsText(text: String)
    fun setTtsVoiceStyle(style: String)
    fun setTtsLang(lang: String)
    fun setTtsTotalSteps(steps: Int)
    fun setTtsSpeed(speed: Float)
    fun requestTtsSynthesis()
}
