package dev.nilp0inter.subspace.ui

interface PttUiActions {
    fun requestPermissions()
    fun requestManageExternalStorage()
    fun pickCaptainsLogDirectory()
    fun openBluetoothSettings()
    fun scanForDevice()
    fun pairTarget()
    fun connectSerial()
    fun retry()
    fun disconnectSerial()
    fun setCaptainsLogSaveVoice(enabled: Boolean)
    fun setCaptainsLogSaveText(enabled: Boolean)
    fun setCaptainsLogEnabled(enabled: Boolean)
    fun setDebugChannelEnabled(enabled: Boolean)
    fun setDebugChannelMode(mode: dev.nilp0inter.subspace.model.DebugMode)
    fun setTtsText(text: String)
    fun setTtsVoiceStyle(style: String)
    fun setTtsLang(lang: String)
    fun setTtsTotalSteps(steps: Int)
    fun setTtsSpeed(speed: Float)
    fun requestTtsSynthesis()
    fun setSttTtsVoiceStyle(style: String)
    fun setSttTtsLang(lang: String)
    fun setSttTtsTotalSteps(steps: Int)
    fun setSttTtsSpeed(speed: Float)
}
