package dev.nilp0inter.subspace.ui

interface PttUiActions {
    fun requestPermissions()
    fun requestManageExternalStorage()
    fun pickJournalDirectory()
    fun openBluetoothSettings()
    fun scanForDevice()
    fun pairTarget()
    fun connectSerial()
    fun retry()
    fun disconnectSerial()
    fun setJournalSaveVoice(enabled: Boolean)
    fun setJournalSaveText(enabled: Boolean)
    fun setActiveChannel(id: String)
    fun setDebugChannelMode(mode: dev.nilp0inter.subspace.model.DebugMode)
    fun navigateToJournalConfig()
    fun navigateToDebugConfig()
    fun navigateBack()
    fun setTtsText(text: String)
    fun setTtsVoiceStyle(style: String)
    fun setTtsLang(lang: String)
    fun setTtsTotalSteps(steps: Int)
    fun setTtsSpeed(speed: Float)
    fun requestTtsSynthesis()
    fun setSttTtsVoiceStyle(style: String)
    fun setSttTtsLang(lang: String)
    fun setSttTtsTotalSteps(steps: Int)
    fun setSttTtsSpeed(speed: Float)
}
